import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
          <link rel="icon" href="Images/logo.png" type="image/x-icon">
    <link rel="shortcut icon" href="Images/logo.png" type="image/x-icon">
    <link rel="apple-touch-icon" sizes="180x180" href="Images/logo.png">
    <link rel="icon" type="image/png" sizes="32x32" href="Images/logo.png">
    <link rel="icon" type="image/png" sizes="16x16" href="Images/logo.png">
    <link rel="manifest" href="/site.webmanifest">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
